controllers:
    resource: ../src/Controller/
    type: attribute



# config/routes/annotations.yaml
#api_post_edit:

app_api_login :
    path:       /login
    controller: App\Controller\ApiLoginController::login
    methods:    POST


register :
    path:       /register
    controller: App\Controller\RegisterController::register
    methods:    POST

